In [1]:
%env CUDA_VISIBLE_DEVICES=0
%env XLA_PYTHON_CLIENT_PREALLOCATE=false

env: CUDA_VISIBLE_DEVICES=0
env: XLA_PYTHON_CLIENT_PREALLOCATE=false


In [2]:
import brax
from brax import jumpy as jp
from brax.envs import env
import jax.numpy as jnp
import jax
from brax.envs import wrappers
import numpy as np
from brax.envs import humanoid

In [3]:
key = jax.random.PRNGKey(777)
key_envs = jax.random.split(key, 1)

In [4]:
from es_map.my_brax_envs import brax_envs
        

In [47]:
#env = brax_envs.DirectionalHumanoid()
env = humanoid.Humanoid()
env = wrappers.EpisodeWrapper(env, episode_length=1000, action_repeat=1)
env = wrappers.VectorWrapper(env, batch_size=10) # for each iteration, we evaluate the children and the parent performance in parallel
env = wrappers.AutoResetWrapper(env) # not sure if this is nessasary, we only look at the first episode
#env = wrappers.VectorGymWrapper(env) 
env

In [50]:
state = env.reset(key)
type(state)

brax.envs.env.State

In [46]:
env._state.obs

jaxlib.xla_extension.DeviceArray

In [11]:
env = brax_envs.DirectionalHumanoid()

In [32]:
env = humanoid.Humanoid()

In [33]:
state = env.reset(key)

In [37]:
state.qp.pos

array([[ 0.00000000e+00,  0.00000000e+00,  1.24404382e+00],
       [ 1.45984871e-02,  2.09814643e-04,  9.88878467e-01],
       [ 7.70314353e-02,  1.65541916e-03,  8.36154882e-01],
       [ 9.33636416e-02, -9.78395111e-02,  7.98286458e-01],
       [ 1.00315547e-01, -8.67310428e-02,  3.97192330e-01],
       [ 9.09667975e-02,  1.02138981e-01,  7.99976724e-01],
       [ 9.66054598e-02,  9.31103282e-02,  3.98776815e-01],
       [ 0.00000000e+00, -1.70000002e-01,  1.30404381e+00],
       [ 1.18477987e-01, -4.15513617e-01,  1.15276240e+00],
       [ 0.00000000e+00,  1.70000002e-01,  1.30404381e+00],
       [ 1.19111008e-01,  4.13431582e-01,  1.14992166e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [25]:
angle = jax.random.uniform(key, shape=[1], minval=-np.pi, maxval=np.pi)
direction = jnp.concatenate([jnp.cos(angle),jnp.sin(angle)])
direction.shape


(2,)

In [8]:
state = my_env.reset(key)

In [18]:
info = state.info
info["fitness"] = 5

In [22]:
#state.replace(info=info)

In [11]:
from brax.envs import wrappers
my_env = wrappers.EpisodeWrapper(my_env, episode_length=1000, action_repeat=1)
my_env = wrappers.VectorWrapper(my_env, batch_size=10) # for each iteration, we evaluate the children and the parent performance in parallel
my_env = wrappers.AutoResetWrapper(my_env) # not sure if this is nessasary, we only look at the first episode
my_env = wrappers.VectorGymWrapper(my_env) 

In [13]:
obs = my_env.reset()

In [18]:
my_env._state.info.keys()

dict_keys(['bd_final_pos', 'bd_foot_contacts', 'first_obs', 'first_qp', 'fitness_control_cost_and_survive', 'fitness_directional_distance', 'fitness_distance_walked', 'fitness_forward', 'steps', 'truncation'])

In [40]:
class A:
    @property
    def action_space(self):
        return 5
    
class B(A):
    @property
    def action_space(self):
        return super().action_space+1

In [41]:
a = A()
a.action_space

5

In [42]:
b = B()
b.action_space

6

In [46]:
jnp.array([ [1,0],
                                [1,1],
                                [0,1],
                                [-1,1],
                                [-1,0],
                                [-1,-1],
                                [0,-1],
                                [1,-1] ]) 

DeviceArray([[ 1,  0],
             [ 1,  1],
             [ 0,  1],
             [-1,  1],
             [-1,  0],
             [-1, -1],
             [ 0, -1],
             [ 1, -1]], dtype=int32)

In [48]:
import numpy as np
np.pi

3.141592653589793

In [51]:
angle = jax.random.uniform(key, shape=[1], minval=-np.pi, maxval=np.pi)
direction = jnp.array([jnp.cos(angle),jnp.sin(angle)])

In [57]:
a = 3
b = list(range(5))
b[0:a]

[0, 1, 2]

In [58]:
env = humanoid.Humanoid()

In [60]:
state = env.reset(key)

In [73]:
state = env.step(state,jax.random.normal(key,[env.action_size]))

In [74]:
state.metrics

{'reward_linvel': 0.0003550625329710997,
 'reward_quadctrl': DeviceArray(0.09240411, dtype=float32),
 'reward_alive': 5.0,
 'reward_impact': 0.0}

17

DeviceArray([-1.1558233 ,  0.50814235, -0.58695835, -0.8900643 ,
              0.04154558,  0.13478915, -0.8070986 ,  1.1654325 ,
             -0.04823395, -1.3722824 , -0.05616152, -0.0096882 ,
             -0.91943014, -0.15495552, -0.0483593 , -0.9986773 ,
             -0.849832  ], dtype=float32)

In [82]:
class A:
    const_A = 10
    def __init__(self):
        self.a = self.const_A

In [83]:
a = A()

In [85]:
a.a

10

In [59]:
from brax.envs import wrappers
from es_map.my_brax_envs import brax_envs

env = brax_envs.FelxibleAnt()

env = wrappers.EpisodeWrapper(env, episode_length=1000, action_repeat=1)
env = wrappers.VectorWrapper(env, batch_size=10) # for each iteration, we evaluate the children and the parent performance in parallel
env = wrappers.AutoResetWrapper(env) # not sure if this is nessasary, we only look at the first episode
env = wrappers.VectorGymWrapper(env) 

In [60]:
obs = env.reset()


In [66]:
env._state.info.keys()

dict_keys(['bd_final_pos', 'bd_foot_contacts', 'contact_cum', 'first_obs', 'first_qp', 'fitness_control_cost_and_survive', 'fitness_directional_distance', 'fitness_distance_walked', 'fitness_forward', 'steps', 'truncation'])

In [63]:
env._state.info["bd_final_pos"]


DeviceArray([[0., 0.],
             [0., 0.],
             [0., 0.],
             [0., 0.],
             [0., 0.],
             [0., 0.],
             [0., 0.],
             [0., 0.],
             [0., 0.],
             [0., 0.]], dtype=float32)

In [64]:
env._state.info["bd_foot_contacts"]

DeviceArray([[0., 0., 0., 0.],
             [0., 0., 0., 0.],
             [0., 0., 0., 0.],
             [0., 0., 0., 0.],
             [0., 0., 0., 0.],
             [0., 0., 0., 0.],
             [0., 0., 0., 0.],
             [0., 0., 0., 0.],
             [0., 0., 0., 0.],
             [0., 0., 0., 0.]], dtype=float32)

In [29]:
a = {
    "aa" : np.ones(4),
    "bb" : np.zeros(5),
}
np.save("test.npy",a)

In [30]:
b = np.load("test.npy",allow_pickle=True)

In [52]:
np.savez("test2.npy",cc=a["aa"],bb=a["bb"])

In [53]:
b = np.load("test2.npy.npz")

In [57]:
dict(b)

{'cc': array([1., 1., 1., 1.]), 'bb': array([0., 0., 0., 0., 0.])}

TypeError: 'aa' is an invalid keyword argument for print()

In [49]:
import os
os.getcwd()

'/home/userfs/a/ak1774/workspace/evolvability_map_elites/evolvability_map_elites'