In [1]:
import os
os.environ["MKL_NUM_THREADS"] = "1" 
os.environ["NUMEXPR_NUM_THREADS"] = "1" 
os.environ["OMP_NUM_THREADS"] = "1" 

import numpy as np
import matplotlib.pyplot as plt
import torch

import gym
import QDgym

In [2]:
import os
import numpy as np
from gym.envs.mujoco import mujoco_env
from gym import utils
from mujoco_py.generated import const

In [3]:
from es_map.interaction import custom_gym
from es_map.interaction import interaction

In [8]:
config = {
    "env_id" : "DamageAnt-v2",
    "policy_args" : {
        "init" : "normc",
        "layers" :[256, 256],
       "activation" : 'tanh',
       "action_noise" : 0.01,
    },
    "env_args" : {
        "use_norm_obs" : True,
    },
}

In [9]:
env = interaction.Ant(config)

In [10]:
env.model
theta = env.initial_theta()

In [11]:
%%time
random_state = np.random.RandomState()

env.rollout(theta,random_state=random_state,render=False)
#theta, random_state, eval=False, obs_mean=None, obs_std=None, render=False

CPU times: user 499 ms, sys: 8.97 ms, total: 508 ms
Wall time: 507 ms


(998.1290099107453,
 999,
 array([0.776, 0.88 , 0.707, 0.738]),
 0.005149554905799588,
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 0)

In [27]:
for a in env.model.weight:
    print(a.shape)

(376, 256)
(256, 256)
(256, 17)


In [81]:
a = np.random.RandomState()

In [17]:
a.seed(5)

In [82]:
a.rand()

0.44729995513369003

In [19]:
from pyvirtualdisplay import Display

virtual_display = Display(visible=0, size=(1400, 900))
virtual_display.start()

EasyProcessError: start error <EasyProcess cmd_param=['Xvfb', '-help'] cmd=['Xvfb', '-help'] oserror=[Errno 2] No such file or directory: 'Xvfb' return_code=None stdout="None" stderr="None" timeout_happened=False>

In [34]:
a = np.random.randint(0,4,5)

In [37]:
a.size

5

In [42]:
list(range(0,11,10))

[0, 10]

In [39]:
a = list(range(15))

In [43]:
a[10:20]

[10, 11, 12, 13, 14]

In [2]:
from dask.distributed import Client
import dask

In [3]:
import os
os.chdir("/scratch/ak1774/runs")

In [4]:
client = Client()

In [53]:
dask.config.get("temporary_directory")

In [10]:
central_theta = np.zeros(1000000)

In [11]:
indicies = range(100)


In [8]:
def func(i,c):
    from es_map.interaction import interaction
    return np.sum(c)/i

def func2(i,c,config):
    from es_map.interaction import interaction
    return np.sum(c)/i

In [23]:
%%time
central_theta_f = client.scatter(central_theta,broadcast=True)
res = client.map(func,indicies,c=central_theta_f)
res = client.gather(res)

CPU times: user 199 ms, sys: 10.9 ms, total: 210 ms
Wall time: 219 ms


In [24]:
%%time
central_theta_f = client.scatter(central_theta,broadcast=True)
res = client.map(func2,indicies,c=central_theta_f,config=config)
res = client.gather(res)

CPU times: user 238 ms, sys: 6.19 ms, total: 244 ms
Wall time: 245 ms


In [25]:
%%time
res = client.map(func,indicies,c=central_theta)
res = client.gather(res)

CPU times: user 1.31 s, sys: 49.8 ms, total: 1.36 s
Wall time: 1.2 s


In [61]:
res = client.gather(res)

In [ ]:
np.concatenate

In [75]:
import sys
sys.path

['/home/userfs/a/ak1774/workspace/evolvability_map_elites/evolvability_map_elites',
 '/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '',
 '/scratch/ak1774/vargpu_env/lib/python3.8/site-packages',
 '/scratch/ak1774/vargpu_env/lib/python3.8/site-packages/IPython/extensions',
 '/home/userfs/a/ak1774/.ipython']

In [1]:
import os
os.environ["MKL_NUM_THREADS"] = "1" 
os.environ["NUMEXPR_NUM_THREADS"] = "1" 
os.environ["OMP_NUM_THREADS"] = "1" 


In [2]:
from dask.distributed import Client
import dask
import os
os.chdir("/scratch/ak1774/runs")
client = Client(n_workers=60, threads_per_worker=1)
client

def set_up_worker():
    import os
    os.environ["MKL_NUM_THREADS"] = "1" 
    os.environ["NUMEXPR_NUM_THREADS"] = "1" 
    os.environ["OMP_NUM_THREADS"] = "1" 
    
client.run(set_up_worker)

{'tcp://127.0.0.1:32827': None,
 'tcp://127.0.0.1:33009': None,
 'tcp://127.0.0.1:33091': None,
 'tcp://127.0.0.1:33259': None,
 'tcp://127.0.0.1:33417': None,
 'tcp://127.0.0.1:33469': None,
 'tcp://127.0.0.1:33753': None,
 'tcp://127.0.0.1:34043': None,
 'tcp://127.0.0.1:34381': None,
 'tcp://127.0.0.1:34851': None,
 'tcp://127.0.0.1:35165': None,
 'tcp://127.0.0.1:35195': None,
 'tcp://127.0.0.1:35253': None,
 'tcp://127.0.0.1:35519': None,
 'tcp://127.0.0.1:35701': None,
 'tcp://127.0.0.1:35833': None,
 'tcp://127.0.0.1:36841': None,
 'tcp://127.0.0.1:37405': None,
 'tcp://127.0.0.1:37791': None,
 'tcp://127.0.0.1:37817': None,
 'tcp://127.0.0.1:37837': None,
 'tcp://127.0.0.1:38145': None,
 'tcp://127.0.0.1:38151': None,
 'tcp://127.0.0.1:38495': None,
 'tcp://127.0.0.1:38677': None,
 'tcp://127.0.0.1:39497': None,
 'tcp://127.0.0.1:40019': None,
 'tcp://127.0.0.1:40233': None,
 'tcp://127.0.0.1:40241': None,
 'tcp://127.0.0.1:40591': None,
 'tcp://127.0.0.1:40837': None,
 'tcp://

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import torch

from es_map import es_update
from es_map.interaction import interaction

In [4]:
config = {
    "env_id" : "DamageAnt-v2",
    "policy_args" : {
        "init" : "normc",
        "layers" :[256, 256],
       "activation" : 'tanh',
       "action_noise" : 0.01,
    },
    "env_args" : {
        "use_norm_obs" : True,
    },
    "ES_popsize" : 2000,
    "ES_sigma" : 0.01,
    
    # DISTRIBUTED SETTING
    "ES_EVALUATION_BATCH_SIZE" : 10,
}

In [5]:
env = interaction.build_interaction_module(config["env_id"],config)

In [6]:
theta = env.initial_theta()

In [11]:
%%time
for _ in range(10):
    es_update.evaluate_individual_local(theta,obs_mean=None,obs_std=None,eval=False,config=config)

CPU times: user 5.72 s, sys: 536 ms, total: 6.25 s
Wall time: 5.74 s


In [12]:
%%time
res = [client.submit(es_update.evaluate_individual_local,theta,obs_mean=None,obs_std=None,eval=False,config=config) for _ in range(10)]
res = client.gather(res)

CPU times: user 613 ms, sys: 166 ms, total: 779 ms
Wall time: 1.83 s


In [7]:
%%time
res = es_update.es_evaluate_children(client,central_theta=theta,obs_mean=env.model.obs_stats.mean,
                                                         obs_std=env.model.obs_stats.std,
                                                         config=config)

mean batch time is:  14.45363800406456
CPU times: user 18.4 s, sys: 5.89 s, total: 24.3 s
Wall time: 57.9 s


In [46]:
res

{'noise_descriptors': [(15536287, 1),
  (86398986, 1),
  (3931112, 1),
  (61850656, 1),
  (9164245, 1),
  (48693134, 1),
  (79238908, 1),
  (46612864, 1),
  (13120791, 1),
  (59288320, 1),
  (30086285, 1),
  (236167, 1),
  (76102586, 1),
  (2045318, 1),
  (43974833, 1),
  (18632230, 1),
  (64373304, 1),
  (47325167, 1),
  (25709399, 1),
  (10212311, 1),
  (15536287, -1),
  (86398986, -1),
  (3931112, -1),
  (61850656, -1),
  (9164245, -1),
  (48693134, -1),
  (79238908, -1),
  (46612864, -1),
  (13120791, -1),
  (59288320, -1),
  (30086285, -1),
  (236167, -1),
  (76102586, -1),
  (2045318, -1),
  (43974833, -1),
  (18632230, -1),
  (64373304, -1),
  (47325167, -1),
  (25709399, -1),
  (10212311, -1)],
 'fitnesses': array([ 994.38593999, 1001.15106617,  997.10004033, 1001.93989278,
        1001.28636351,  991.47081519, 1004.17402391,  991.17894073,
         992.31558875,  996.07138453,  995.53432855, 1003.59383833,
        1002.32417685,  995.50500509,  993.09637882, 1004.11757308,
   

In [6]:
%%time
from es_map.interaction import interaction
env = interaction.build_interaction_module(config["env_id"],config)

CPU times: user 19.4 ms, sys: 4.89 ms, total: 24.3 ms
Wall time: 22.5 ms


In [9]:
%%time
env.rollout( theta, random_state=np.random.RandomState(), eval=False, obs_mean=None, obs_std=None, render=False)

CPU times: user 544 ms, sys: 7.49 ms, total: 552 ms
Wall time: 513 ms


(677.3798546074639,
 999,
 array([0.922, 0.227, 0.942, 0.734]),
 -0.16646408420047717,
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 0)

In [17]:
np.__config__.show()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [17]:
def centered_rank_normalizer(x):
    if len(x.shape) == 1:
        return compute_centered_ranks(x)
    elif len(x.shape) == 2:
        ranked = np.zeros(x.shape)
        for i in range(x.shape[1]):
            ranked[:, i] = compute_centered_ranks(x[:, i])
        return ranked
    raise ValueError("X must have 1 or 2 dimensions")

def compute_ranks(x):
    """
    Returns ranks in [0, len(x))
    Note: This is different from scipy.stats.rankdata, which returns ranks in [1, len(x)].
    """
    assert x.ndim == 1
    ranks = np.empty(len(x), dtype=int)
    ranks[x.argsort()] = np.arange(len(x))
    return ranks


def compute_centered_ranks(x):
    y = compute_ranks(x.ravel()).reshape(x.shape).astype(np.float32)
    y /= x.size - 1
    y -= .5
    return y

In [24]:
x = np.random.randn(29,4)
np.sum(centered_rank_normalizer(x),axis=1)

array([ 0.6071429 ,  0.2142857 , -1.17857143, -0.60714287, -0.07142857,
       -0.74999997, -0.9285714 , -0.5       , -0.5357143 ,  0.78571433,
       -0.07142854,  0.10714284,  0.64285719, -0.3214286 ,  0.50000003,
        1.39285713, -0.42857143, -0.03571433,  0.4285714 ,  0.32142857,
       -0.32142857, -0.46428567, -0.10714287, -0.3214286 ,  1.53571433,
       -0.14285716,  0.57142857, -0.35714287,  0.0357143 ])